name: Dependency review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/dependency-review-action@fddeee1a7ece751b577e409a89057319e3172939 # v4
